build:
  environment:
    php:
      version: 7.3
  dependencies:
    after:
      - wget -O phpunit.phar https://phar.phpunit.de/phpunit-7.5.8.phar
      - chmod +x phpunit.phar
  tests:
    override:
      - command: ./phpunit --coverage-clover=clover.xml
        coverage:
          file:  clover.xml
          format: php-clover
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
  php:
    code_rating: true
    duplication: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true

filter:
  paths: ["src/*"]
