language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
